/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'propiz-primary': '#3a0ca3', // Deep purple as primary color
        'propiz-secondary': '#7209b7', // Medium purple as secondary
        'propiz-light': '#f4f4f4', // Keep light color for contrast
        'propiz-accent': '#4cc9f0', // Light blue accent color
        'propiz-dark': '#240046', // Very dark purple for backgrounds
        'propiz-gradient-start': '#3a0ca3', // For gradients
        'propiz-gradient-end': '#4cc9f0', // For gradients
      },
      fontFamily: {
        'sans': ['Gotham SSm A', 'Gotham SSm B', 'Arial', 'sans-serif'],
      },
      spacing: {
        '0': '0px',
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
        '40': '10rem',
        '48': '12rem',
        '56': '14rem',
        '64': '16rem',
      },
    },
  },
  // Enable all core plugins
  corePlugins: {
    preflight: true,
    container: true,
    space: true,
    divideWidth: true,
    divideColor: true,
    divideStyle: true,
    divideOpacity: true,
    accessibility: true,
    appearance: true,
    backgroundAttachment: true,
    backgroundClip: true,
    backgroundColor: true,
    backgroundImage: true,
    backgroundOpacity: true,
    backgroundPosition: true,
    backgroundRepeat: true,
    backgroundSize: true,
    borderCollapse: true,
    borderColor: true,
    borderOpacity: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxShadow: true,
    boxSizing: true,
    cursor: true,
    display: true,
    flexDirection: true,
    flexWrap: true,
    alignItems: true,
    alignContent: true,
    justifyContent: true,
    alignSelf: true,
    flex: true,
    flexGrow: true,
    flexShrink: true,
    order: true,
    float: true,
    clear: true,
    fontFamily: true,
    fontWeight: true,
    height: true,
    lineHeight: true,
    listStylePosition: true,
    listStyleType: true,
    margin: true,
    maxHeight: true,
    maxWidth: true,
    minHeight: true,
    minWidth: true,
    objectFit: true,
    objectPosition: true,
    opacity: true,
    outline: true,
    overflow: true,
    overscrollBehavior: true,
    padding: true,
    placeholderColor: true,
    placeholderOpacity: true,
    pointerEvents: true,
    position: true,
    inset: true,
    resize: true,
    rotate: true,
    scale: true,
    skew: true,
    tableLayout: true,
    textAlign: true,
    textColor: true,
    textOpacity: true,
    textOverflow: true,
    textTransform: true,
    transform: true,
    transformOrigin: true,
    transitionProperty: true,
    transitionTimingFunction: true,
    transitionDuration: true,
    transitionDelay: true,
    userSelect: true,
    verticalAlign: true,
    visibility: true,
    whitespace: true,
    width: true,
    wordBreak: true,
    zIndex: true,
    gap: true,
    gridAutoFlow: true,
    gridTemplateColumns: true,
    gridAutoColumns: true,
    gridColumn: true,
    gridColumnStart: true,
    gridColumnEnd: true,
    gridTemplateRows: true,
    gridAutoRows: true,
    gridRow: true,
    gridRowStart: true,
    gridRowEnd: true,
    fontVariantNumeric: true,
    letterSpacing: true,
    fontSize: true,
  },
  plugins: [],
}